//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace CrmSvcUtil.Client.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("CrmSvcUtil.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        internal static string CrmLogOnForm_mgr_ConnectionCheckComplete_Login_Failure {
            get {
                return ResourceManager.GetString("CrmLogOnForm_mgr_ConnectionCheckComplete_Login_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from Connection Manager.
        /// </summary>
        internal static string CrmLogOnForm_mgr_ConnectionCheckComplete_Notification_from_Connection_Manager {
            get {
                return ResourceManager.GetString("CrmLogOnForm_mgr_ConnectionCheckComplete_Notification_from_Connection_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        internal static string CrmLogOnForm_Window_Loaded_Auto_Login {
            get {
                return ResourceManager.GetString("CrmLogOnForm_Window_Loaded_Auto_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.cs.
        /// </summary>
        internal static string MainWindow_CheckBoxCreateClassPerItem_Checked_Entities_cs {
            get {
                return ResourceManager.GetString("MainWindow_CheckBoxCreateClassPerItem_Checked_Entities_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Organizations.
        /// </summary>
        internal static string Organizations_OrganizationListView_Loaded_Loading_Organizations {
            get {
                return ResourceManager.GetString("Organizations_OrganizationListView_Loaded_Loading_Organizations", resourceCulture);
            }
        }
    }
}
